### ISSUE TITLE
Does not boot V1 image

### ISSUE THREAD

**Issue by Fever-Wits** [avafinger/nanopi-r6s-debian11-xfce#1]
Hello,
I downloaded image version 1, with dd if=./image of=/dev/myflash bs=1M status=progress I saved the image to the memory card.
When booting the NanoPi R6S with an image version 1 memory stick already burned in, I see a black screen with a flashing marker.
I waited 30 min and no change.

Where can I go wrong?

**Comment by avafinger** [comment]
You can try ssh:

You can find in your router what the IP is given, the board has DHCP enabled for all three eth.

`ssh rock@xxx.xxx.xxx.xxx`

user/pwd
rock/rock

**Comment by avafinger** [comment]
* What is your display brand/model/resolution?
* Are you using any adapter or HDMI?
* What power brick?

**Comment by Fever-Wits** [comment]
Hello,

I realized my mistake, image V1 you use to copy to internal flash drive, image V2 you made.
I will ask if possible for information on exactly how you made this V2 image.
I'll be using a NanoPi R6S, and I'd like to make a clean image, no graphics environment.
If you think that the place for the information I am asking for is not here, please write to a.hristow@gmail.com

Regards,

**Comment by avafinger** [comment]
**V1** image is for SD card, **V2** is for the eMMC.
But you can flash **V1** to **eMMC** and change a few things.

In theory, this should work:

* Extract and get idbloader.img and u-boot.itb from **V2** tarball

* Boot from **SD card** with **V1** and with the mentioned files
* Umount any partition in /dev/mmcblk2*
```
sudo su
export emmc=/dev/mmcblk2
dd if=./image of=${emmc} bs=1M status=progress
sync
sleep 3
## get the idbloader.img and u-noot from V2 and write it to eMMC
## boot loader
dd if=./idbloader.img of=${emmc} seek=64 conv=notrunc
sleep 3
sync
dd if=./u-boot.itb of=${emmc} seek=16384 conv=notrunc
sleep 2
sync
##
## change boot device
##
mkdir eboot
mount ${emmc}p1 ./eboot
mcedit ./eboot/extlinux/extlinux.conf
## change mmcblk0p2 to /mmcblk2p2
## like so:
## rootfstype=ext4 rootwait root=/dev/mmcblk0p2 to rootfstype=ext4 rootwait root=/dev/mmcblk2p2
sync
umount eboot

mkdir erootfs
mount ${emmc}p2 ./erootfs
## edit /etc/fstab
mcedit ./erootfs/etc/fstab
## change mmcblk0p to mmcblk2p
# /dev/mmcblk2p2	/	ext4	defaults,noatime,nodiratime,commit=600,errors=remount-ro,x-gvfs-hide		0		2
# /dev/mmcblk2p1	/boot	vfat	defaults,x-systemd.automount	0	0	
sync
umount erootfs
## shutdown
shutdown -h now
##
## remove power
## remove SD card

##
## Apply power, this will boot from eMMC (hopefully)
## Now you end up having 8GB eMMC
## Extend the eMMC to reclaim the remaining space to have 32GB

```
**Note:
Make sure you know what you are doing and know how to extend the eMMC.
There are some scripts around the internet to do this automagically, but i recommend doing it manually**

When you are done, please, close the issue.

**Comment by Fever-Wits** [comment]
Hi, 
thanks for the info.  
Greetings
